spring:
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
    liquibase-schema: drones
    default-schema: drones

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=drones
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: false
    properties:
      hibernate:
        default_schema: drones
        format_sql: true

  cloud:
    stream:
      bindings:
        orderPublisher:
          destination: order
        orderSubscriber:
          destination: order
      kafka:
        binder:
          defaultBrokerPort: 9092

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    logfile:
      enabled: true
  health:
    defaults:
      enabled: true